[versions]
kotlin = "1.9.23"
kotlinComposePlugin = "1.5.2"
coreKtx = "1.16.0"
composeBom = "2024.04.01"


[libraries]
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }

[plugins]
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlinComposePlugin" }
android-application = { id = "com.android.application", version = "8.8.1" }
google-services = { id = "com.google.gms.google-services", version = "4.4.2" }
